documentation:
  - docs/**/*
  - CONTRIBUTING.md
  - CONTRIBUTORS.md
  - LICENSE
  - MISSION_STATEMENT.md
  - README.md
  - README_DOCKER.md

examples:
  - example/**/*

github:
  - .github/**/*

license-templates:
  - license-templates/**/*

scripts:
  - scripts/**/*

src:
  - src/**/*

tests:
  - .clang-format
  - .dockerignore
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .hound.yml
  - .mergify.yml
  - .pre-commit-config.yaml
  - .prettierignore
  - .prettierrc
  - CMakeLists.txt
  - CODEOWNERS
  - Dockerfile
  - Makefile
  - codespell.txt
  - docker-compose.yml
  - mlc_config.json
  - test/**/*

tmp:
  - tmp/**/*
