documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - docs/**/*
              - CONTRIBUTING.md
              - CONTRIBUTORS.md
              - LICENSE
              - MISSION_STATEMENT.md
              - README.md
              - README_DOCKER.md

examples:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - example/**/*

github:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - .github/**/*

license-templates:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - license-templates/**/*

scripts:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - scripts/**/*

src:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - src/**/*

tests:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - .clang-format
              - .dockerignore
              - .editorconfig
              - .gitattributes
              - .gitignore
              - .hound.yml
              - .mergify.yml
              - .pre-commit-config.yaml
              - .prettierignore
              - .prettierrc
              - CMakeLists.txt
              - CODEOWNERS
              - Dockerfile
              - Makefile
              - codespell.txt
              - docker-compose.yml
              - mlc_config.json
              - test/**/*

tmp:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - tmp/**/*
