<start>        ::= <parnet_items> | <empty>

<parnet_items> ::= <parent_item> <parnet_items>

<parent_item>  ::= <function>
                 | <global_variable>
                 
<function>     ::= <function_prototype> <identifier> <function_arguments> <block>

<function_prototype> ::= <datatype> | <empty>

<function_arguments> ::= <function_arguments> "," <function_argument>

<datatype_primary>   :: = I8 I16 I32 I64 F32 F64 U8 U16 U32 U64 STRING CHAR

<datatype>           ::= <datatype_primary>
                       | <datatype_primary> "[" "]"
                       | IDENTIFIER ; e.g: struct and user defined types

<function_argument>  ::= <datatype> IDENTIFIER

<block>        ::= "{" <statements> "}"

<statements>   ::= <statements> <statement>
                 

<statement>    ::= <statement_return>
                 | <statement_expression>
                 | <statement_if>
                 | <statement_for>
                 | <statement_while>
                 | <statement_dowhile>

<statement_for>  ::= FOR <expression> <block>

<statement_while>::= WHILE <expression> <block>

<statement_dowhile>::= DO  <block> while <expression>

<expression>   ::= <term> "+" <expression>
                 | <term>

<term>         ::= <factor> "*" <term>
                 | <factor>

<factor>       ::= "(" <expression> ")"
                 | <const>

<const>        ::= NUMBER | STRING | IDENTIFIER
