<start>        ::= <parnet_items> | <empty>

<parnet_items> ::= <parent_item> <parnet_items>

<parent_item>  ::= <function>
                 | <global_variable>
                 
<function>     ::= <function_prototype> <identifier> <function_arguments> <statements>

<function_prototype> ::= <datatype> | <empty>

<function_arguments> ::= <function_arguments> "," <function_argument>

<function_argument>  ::= <datatype> IDENTIFIER

<statements>   ::= <statements> <statement>

<statement>    ::= <statement_return>
                 | <statement_expression>
                 | <statement_if>
                 | <statement_for>
                 | <statement_while>
                 | <statement_dowhile>

<statement_for>  ::= FOR <expression> <statements>

<statement_while>::= WHILE <expression> <statements>

<statement_dowhile>::= DO  <statements> while <expression>

<expression>   ::= <term> "+" <expression>
                 | <term>

<term>         ::= <factor> "*" <term>
                 | <factor>

<factor>       ::= "(" <expression> ")"
                 | <const>

<const>        ::= NUMBER | STRING | IDENTIFIER
