/*
 * Copyright 2021 - Max Base, <maxbasecode@gmail.com>
 * This file is part of One Programming Language.
 *
 * one-language is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * one-language is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with one-language.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

DEF(TOK_OP_AND1, "and")
DEF(TOK_OP_OR1, "or")
DEF(TOK_OP_ADD, "+")
DEF(TOK_OP_MIN, "-")
DEF(TOK_OP_POW1, "^")
DEF(TOK_OP_POW2, "**")
DEF(TOK_OP_MUL, "*")
DEF(TOK_OP_DIV, "/")
DEF(TOK_OP_BITWISE_OR, "|")
DEF(TOK_OP_BITWISE_AND, "&")
DEF(TOK_OP_G, ">")
DEF(TOK_OP_L, "<")
DEF(TOK_OP_OR2, "||")
DEF(TOK_OP_AND2, "&&")
DEF(TOK_OP_SHIFT_LEFT, ">>")
DEF(TOK_OP_SHIFT_RIGHT, "<<")
DEF(TOK_OP_NOT1, "!")
DEF(TOK_OP_NOT2, "not")
DEF(TOK_OP_GE, ">=")
DEF(TOK_OP_LE, "<=")
DEF(TOK_OP_NEQ, "!=")
DEF(TOK_OP_NEQT, "!==")
DEF(TOK_OP_DEFINE, "=")
DEF(TOK_OP_EQ, "==")
DEF(TOK_OP_EQT, "===")
DEF(TOK_END_OPERATION, "\ntokendoperation")
DEF(TOK_I8, "i8")
DEF(TOK_I16, "i16")
DEF(TOK_I32, "i32")
DEF(TOK_I64, "i64")
DEF(TOK_I128, "i128")
DEF(TOK_UI8, "ui8")
DEF(TOK_UI16, "ui16")
DEF(TOK_UI32, "ui32")
DEF(TOK_UI64, "ui64")
DEF(TOK_F32, "f32")
DEF(TOK_F64, "f64")
DEF(TOK_BOOL, "bool")
DEF(TOK_ACHAR, "achar")
DEF(TOK_CHAR, "char")
DEF(TOK_STRING, "string")
DEF(TOK_NULL, "null")
DEF(TOK_END_VARAIBLE_TYPE, "\ntokendvaraibletype")
DEF(TOK_START_BLOCK_COMMENT, "/*")
DEF(TOK_END_BLOCK_COMMENT, "*/")     
DEF(TOK_LINE_COMMENT, "//")               
DEF(TOK_SHIELD, "\\")     
DEF(TOK_COLONCOLON, "::")
DEF(TOK_COLON, ":")
DEF(TOK_DOT, ".")
DEF(TOK_DOTDOT, "..")
DEF(TOK_DOTDOTDOT, "...")
DEF(TOK_SEMICOLON, ";")
DEF(TOK_VIRGOL, ",")
DEF(TOK_PARENT_LEFT, "(")
DEF(TOK_PARENT_RIGHT, ")")
DEF(TOK_BRACKET_LEFT, "[")
DEF(TOK_BRACKET_RIGHT, "]")
DEF(TOK_SECTION_LEFT, "{")
DEF(TOK_SECTION_RIGHT, "}")
DEF(TOK_CHOICE, "?")
DEF(TOK_IF, "if")
DEF(TOK_ELSE, "else")
DEF(TOK_AS, "as")
DEF(TOK_BREAK, "break")
DEF(TOK_CONTINUE, "continue")
DEF(TOK_SWITCH, "switch")
DEF(TOK_MATCH, "match")
DEF(TOK_CASE, "case")
DEF(TOK_DEFAULT, "default")
DEF(TOK_STRUCT, "struct")
DEF(TOK_ENUM, "enum")
DEF(TOK_UNION, "union")
DEF(TOK_IMPORT, "import")
DEF(TOK_DO, "do")
DEF(TOK_WHILE, "while")
DEF(TOK_REPEAT, "repeat")
DEF(TOK_FOREACH, "foreach")
DEF(TOK_FOR, "for")
DEF(TOK_RET, "ret")
DEF(TOK_PRINT, "_")
DEF(TOK_PRINTLN, "__")
DEF(TOK_END_KEYWORD, "\ntokendokeyword")
